### ISSUE TITLE
Conditional Binding

### ISSUE THREAD

**Issue by 4w415c** [AmrDeveloper/EasyAdapter#2]
How do I set a text or image based on another fields value? Like when a boolean variable is true I want to set one text but it it's false I want to set another.

**Comment by AmrDeveloper** [comment]
Hello @4w415c,

Thank you for your issue, I am planning to create a way to add multi conditions not only one and i will create it soon

Thanks
Amr Hesham

**Comment by AmrDeveloper** [comment]
Please Check The new release with Optional condition for each Bind annotation and you can add more than one condition with operators

Thanks for your suggestion 👍🏻

**Comment by 4w415c** [comment]
Thank you. I will try it out.
